ALTER TABLE marches ADD COLUMN gather_mode VARCHAR(10) NOT NULL DEFAULT 'auto';
ALTER TABLE marches ADD COLUMN gather_start_at BIGINT NULL;
ALTER TABLE marches ADD COLUMN gather_stopped BOOLEAN NOT NULL DEFAULT FALSE;
